<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../visualizer/Models/*.cs" Link="Visualizer/Models/%(Filename)%(Extension)" />
    <Compile Include="../visualizer/ViewModels/*.cs" Link="Visualizer/ViewModels/%(Filename)%(Extension)" />
    <None Update="Fixtures/*.csv" CopyToOutputDirectory="PreserveNewest" />
    <None Update="Fixtures/*.json" CopyToOutputDirectory="PreserveNewest" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <ProjectReference Include="../sources/EllipticCurves.csproj" />
  </ItemGroup>
</Project>
