using System;
using System.Collections.Generic;
using System.Numerics;
using System.Threading;
using static EllipticCurves.RealArithmetic;

namespace EllipticCurves
{
    public sealed partial class EllipticCurveQ
    {
        /// <summary>Logarithmic x-height log max(|numerator(x)|,denominator(x)); zero at infinity.</summary>
        public RealEnclosure NaiveHeight(EllipticCurvePoint point, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            ValidateHeightPoint(point); var c = RealContext(options, cancellationToken);
            return point.IsInfinity ? c.I(0) : c.Finish(c.Log(c.I(new BigRational(BigInteger.Max(BigInteger.Abs(point.X.Num), point.X.Den)))));
        }

        /// <summary>Canonical height lim 4^(-n) h_x(2^n P), in the Cremona/LMFDB normalization.</summary>
        public RealEnclosure CanonicalHeight(EllipticCurvePoint point, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            ValidateHeightPoint(point); var c = RealContext(options, cancellationToken);
            if (point.IsInfinity) return c.I(0);
            var map = GetMinimalModelIsomorphism(cancellationToken);
            return c.Finish(CanonicalHeightOnMinimal(map.Target, map.Map(point), c));
        }

        /// <summary>Finite local height on the reduced global minimal model. Infinity is outside its domain.</summary>
        public RealEnclosure LocalHeight(EllipticCurvePoint point, BigInteger prime, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            ValidateHeightPoint(point);
            if (point.IsInfinity) throw new ArgumentException("Local height is undefined at infinity.", nameof(point));
            if (!NativeNumberTheory.IsPrime(prime, cancellationToken)) throw new ArgumentOutOfRangeException(nameof(prime));
            var c = RealContext(options, cancellationToken); var map = GetMinimalModelIsomorphism(cancellationToken);
            return c.Finish(c.Mul(c.I(LocalHeightCoefficient(map.Target, map.Map(point), prime)), c.Log(c.I(new BigRational(prime)))));
        }

        /// <summary>Archimedean local height on the reduced global minimal model; undefined at infinity.</summary>
        public RealEnclosure ArchimedeanHeight(EllipticCurvePoint point, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            ValidateHeightPoint(point);
            if (point.IsInfinity) throw new ArgumentException("Local height is undefined at infinity.", nameof(point));
            var c = RealContext(options, cancellationToken); var map = GetMinimalModelIsomorphism(cancellationToken);
            return c.Finish(RealLocalHeight(map.Target, map.Map(point).X, c));
        }

        /// <summary>Half of h(P+Q)-h(P)-h(Q), with a proved enclosure.</summary>
        public RealEnclosure HeightPairing(EllipticCurvePoint p, EllipticCurvePoint q, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            var matrix = HeightPairingMatrix(new[] { p, q }, options, cancellationToken); return matrix[0, 1];
        }

        /// <summary>Height pairing matrix of the supplied points; no basis assumption is made.</summary>
        public RealEnclosure[,] HeightPairingMatrix(IReadOnlyList<EllipticCurvePoint> points, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            if (points == null) throw new ArgumentNullException(nameof(points));
            var c = RealContext(options, cancellationToken); var map = GetMinimalModelIsomorphism(cancellationToken); var e = map.Target;
            var p = new EllipticCurvePoint[points.Count]; var matrix = new RealEnclosure[p.Length, p.Length];
            for (int i = 0; i < p.Length; i++) { ValidateHeightPoint(points[i]); p[i] = map.Map(points[i]); matrix[i, i] = CanonicalHeightOnMinimal(e, p[i], c); }
            for (int i = 0; i < p.Length; i++) for (int j = 0; j < i; j++)
                matrix[j, i] = matrix[i, j] = c.Div(c.Sub(c.Sub(CanonicalHeightOnMinimal(e, e.Add(p[i], p[j]), c), matrix[i, i]), matrix[j, j]), c.I(2));
            foreach (var entry in matrix) c.Finish(entry);
            return matrix;
        }

        /// <summary>Regulator of the subgroup generated by supplied independent points, modulo torsion.
        /// This is the curve regulator only when the points form a full Mordell-Weil basis.
        /// Throws if positive definiteness cannot be proved at the requested precision.</summary>
        public RealEnclosure Regulator(IReadOnlyList<EllipticCurvePoint> points, RealComputationOptions options = null, CancellationToken cancellationToken = default)
        {
            var c = RealContext(options, cancellationToken); var matrix = HeightPairingMatrix(points, options, cancellationToken); var determinant = c.I(1);
            for (int k = 0; k < points.Count; k++)
            {
                if (matrix[k, k].LowerBound <= 0) throw new ArithmeticException("Point independence was not certified; points may be dependent or precision insufficient.");
                determinant = c.Mul(determinant, matrix[k, k]);
                for (int i = k + 1; i < points.Count; i++) for (int j = i; j < points.Count; j++)
                    matrix[j, i] = matrix[i, j] = c.Sub(matrix[i, j], c.Div(c.Mul(matrix[i, k], matrix[j, k]), matrix[k, k]));
            }
            return c.Finish(determinant);
        }

        private void ValidateHeightPoint(EllipticCurvePoint p)
        { if (IsSingular) throw new InvalidOperationException("Heights require a nonsingular curve."); if (!IsOnCurve(p)) throw new ArgumentException("Point is not on this curve.", nameof(p)); }
        private static RealArithmetic RealContext(RealComputationOptions o, CancellationToken token)
        { token.ThrowIfCancellationRequested(); return new RealArithmetic((o ?? new RealComputationOptions()).Snapshot(), token); }

        internal static RealEnclosure CanonicalHeightOnMinimal(EllipticCurveQ e, EllipticCurvePoint p, RealArithmetic c)
        {
            c.Token.ThrowIfCancellationRequested();
            if (p.IsInfinity) return c.I(0);
            var value = c.Add(RealLocalHeight(e, p.X, c), c.Log(c.I(new BigRational(p.X.Den))));
            foreach (var prime in NativeNumberTheory.Factor(e.Discriminant.Num, c.Token).Keys)
            {
                c.Token.ThrowIfCancellationRequested();
                if (p.X.Den % prime != 0) value = c.Add(value, c.Mul(c.I(LocalHeightCoefficient(e, p, prime)), c.Log(c.I(new BigRational(prime)))));
            }
            // The global height is nonnegative, even when local terms are negative.
            if (value.UpperBound < 0) throw new ArithmeticException("Computed enclosure contradicts nonnegativity of the canonical height.");
            return new RealEnclosure(Max(0, value.LowerBound), value.UpperBound);
        }

        // Silverman's local formulas on a minimal model (Cremona III.4, Prop. 3.4.1).
        private static BigRational LocalHeightCoefficient(EllipticCurveQ e, EllipticCurvePoint p, BigInteger prime)
        {
            int V(BigRational a) => a.IsZero ? int.MaxValue / 4 : Valuation(a.Num, prime) - Valuation(a.Den, prime);
            var x = p.X; var y = p.Y;
            int a = V(3 * x * x + 2 * e.A2 * x + e.A4 - e.A1 * y), b = V(2 * y + e.A1 * x + e.A3);
            if (a <= 0 || b <= 0) return Math.Max(0, -V(x));
            int n = Valuation(e.Discriminant.Num, prime);
            if (V(e.C4) == 0) { var m = Min(b, new BigRational(n, 2)); return m * (m - n) / n; }
            int d = V(3 * BigRational.Pow(x, 4) + e.B2 * BigRational.Pow(x, 3) + 3 * e.B4 * x * x + 3 * e.B6 * x + e.B8);
            return (long)d >= 3L * b ? new BigRational(-2L * b, 3) : new BigRational(-d, 4);
        }

        // Tate series with two coordinate charts x and x+1. Each chart is used
        // only after proving |1/x| <= 2. The truncation estimate is Silverman's
        // theorem quoted in Cremona III.4. Outward rounding also includes all
        // arithmetic and logarithm errors, not merely the series tail.
        private static RealEnclosure RealLocalHeight(EllipticCurveQ e, BigRational x, RealArithmetic c)
        {
            var b = new[] { e.B2, e.B4, e.B6, e.B8 };
            var shifted = new[] { b[0] - 12, b[1] - b[0] + 6, b[2] - 2 * b[1] + b[0] - 4, b[3] - 3 * b[2] + 3 * b[1] - b[0] + 3 };
            var h = Max(4, Max(b[0].Abs(), Max(2 * b[1].Abs(), Max(2 * b[2].Abs(), b[3].Abs()))));
            int digits = c.Options.DecimalDigits + c.Options.GuardDigits;
            int iterations = (5 * digits + 2) / 3 + 1 + BitLength(7 + 2 * BitLength(h.Num));
            if (iterations > c.Options.MaxIterations) throw new ArithmeticException("Height series iteration limit reached.");
            bool original = x.Abs() >= new BigRational(1, 2);
            var parameter = c.I(1 / (original ? x : x + 1)); var value = c.Log(c.I((original ? x : x + 1).Abs()));
            BigRational weight = 1;
            for (int k = 0; k < iterations; k++)
            {
                c.Token.ThrowIfCancellationRequested(); weight /= 4;
                var v = original ? b : shifted;
                var t2 = c.Mul(parameter, parameter); var t3 = c.Mul(t2, parameter); var t4 = c.Mul(t2, t2);
                var w = c.Add(c.Add(c.Mul(c.I(v[2]), t4), c.Mul(c.I(2 * v[1]), t3)), c.Add(c.Mul(c.I(v[0]), t2), c.Mul(c.I(4), parameter)));
                var z = c.Sub(c.I(1), c.Add(c.Add(c.Mul(c.I(v[1]), t2), c.Mul(c.I(2 * v[2]), t3)), c.Mul(c.I(v[3]), t4)));
                var alternative = original ? c.Add(z, w) : c.Sub(z, w);
                if (c.Abs(w).UpperBound > 2 * c.Abs(z).LowerBound)
                {
                    if (c.Abs(w).UpperBound > 2 * c.Abs(alternative).LowerBound) throw new ArithmeticException("Height chart could not be certified; increase PrecisionBits.");
                    z = alternative; original = !original;
                }
                value = c.Add(value, c.Mul(c.I(weight), c.Log(c.Abs(z)))); parameter = c.Div(w, z);
            }
            var error = new BigRational(1, 2 * BigInteger.Pow(10, digits));
            return c.Add(value, new RealEnclosure(-error, error));
        }
    }
}
