using System;
using System.Collections.Generic;
using System.Linq;
using System.Numerics;
using System.Threading;

namespace EllipticCurves
{
    public sealed partial class EllipticCurveQ
    {
        /// <summary>Exactly saturate the subgroup generated by points and E(Q)_tors at the specified primes.
        /// Full rank is not required. Independence is certified by interval heights; work limits return an honest partial result.</summary>
        public SaturationResult Saturate(IReadOnlyList<EllipticCurvePoint> points, IReadOnlyList<int> primes, SaturationOptions options = null, CancellationToken cancellationToken = default)
        {
            if (points == null) throw new ArgumentNullException(nameof(points));
            if (primes == null) throw new ArgumentNullException(nameof(primes));
            options ??= new SaturationOptions();
            long maxWork = options.MaxWork; int maxDegree = options.MaxDivisionDegree, maxEnlargements = options.MaxEnlargements;
            var heightOptions = (options.HeightOptions ?? new RealComputationOptions()).Snapshot();
            if (maxWork < 0 || maxDegree < 4 || maxDegree > 100000 || maxEnlargements < 0) throw new ArgumentOutOfRangeException(nameof(options));
            var requested = primes.Distinct().OrderBy(p => p).ToArray();
            foreach (var prime in requested) if (!NativeNumberTheory.IsPrime(prime, cancellationToken)) throw new ArgumentOutOfRangeException(nameof(primes), "Only primes are allowed.");
            var input = points.ToArray(); foreach (var p in input) ValidateHeightPoint(p);
            cancellationToken.ThrowIfCancellationRequested();
            if (IsSingular) throw new InvalidOperationException("Saturation requires a nonsingular curve.");
            if (input.Length == 0) return new SaturationResult(input, requested, Array.Empty<int>(), true, 1, 0, "The rational torsion subgroup is saturated modulo torsion.");
            var certified = new List<int>(); var budget = new DescentBudget(new RankComputationOptions { MaxDescentWork = maxWork }, cancellationToken);
            BigInteger index = 1;
            try { Regulator(input, heightOptions, cancellationToken); }
            catch (ArithmeticException ex) { return new SaturationResult(input, certified, requested, false, index, 0, ex.Message); }
            if (requested.Length == 0) return new SaturationResult(input, requested, requested, true, 1, 0, "No saturation primes were requested.");
            // Completing the square and translating x gives a short model with u=1.
            var r = -B2 / 12; var map = ChangeModel(1, r, -A1 / 2, -(A3 + r * A1) / 2); var e = map.Target;
            var basis = input.Select(map.Map).ToArray();
            var torsion = e.TorsionPoints.ToArray();
            int enlargements = 0;
            SaturationResult Result(string reason) => new SaturationResult(basis.Select(map.MapBack), certified, requested.Except(certified), true, index, budget.Work, reason);
            try
            {
                foreach (int prime in requested)
                {
                    budget.Step();
                    if (basis.Length == 0) { certified.Add(prime); continue; }
                    if ((long)prime * prime > maxDegree) return Result("Division degree limit reached.");
                    var arithmetic = new DivisionPolynomials(e.A4, e.A6, budget);
                    var equation = arithmetic.Multiplication(prime);
                    var filters = DivisionFilters(e, prime, budget);
                    while (true)
                    {
                        bool enlarged = false;
                        // Projective representatives in F_p^r: first nonzero coordinate = 1.
                        // Testing all torsion translates accounts for E(Q)_tors/p E(Q)_tors.
                        for (int pivot = 0; pivot < basis.Length && !enlarged; pivot++)
                        {
                            var coefficients = new int[basis.Length]; coefficients[pivot] = 1;
                            bool more = true;
                            while (more && !enlarged)
                            {
                                budget.Step(); var target = basis[pivot];
                                for (int i = pivot + 1; i < basis.Length; i++) target = e.Add(target, e.Multiply(basis[i], coefficients[i]));
                                foreach (var t in torsion)
                                {
                                    budget.Step(); var q = e.Add(target, t);
                                    if (q.IsInfinity) throw new InvalidOperationException("Certified independent generators produced a torsion relation.");
                                    if (filters.Any(filter => !filter(q))) continue;
                                    var f = arithmetic.Sub(equation.numerator, arithmetic.Scale(equation.denominator, q.X));
                                    foreach (var x in arithmetic.RationalRoots(f))
                                    {
                                        budget.Step();
                                        if (!BigRational.IsSquare(x * x * x + e.A4 * x + e.A6, out var y)) continue;
                                        var division = new EllipticCurvePoint(x, y);
                                        if (!e.Multiply(division, prime).Equals(q)) division = e.Negate(division);
                                        if (!e.Multiply(division, prime).Equals(q)) continue;
                                        if (enlargements >= maxEnlargements) return Result("Subgroup enlargement limit reached.");
                                        // pQ=P_pivot+sum a_i P_i+T, so replacing the pivot
                                        // preserves containment and enlarges the group by exactly p.
                                        basis[pivot] = division; index *= prime; enlargements++; enlarged = true; break;
                                    }
                                    if (enlarged) break;
                                }
                                int at = pivot + 1;
                                while (at < coefficients.Length && ++coefficients[at] == prime) { coefficients[at] = 0; at++; }
                                more = at < coefficients.Length;
                            }
                        }
                        if (!enlarged) break;
                    }
                    certified.Add(prime);
                }
                return Result("Saturation proved at all requested primes. No claim about unrequested primes or full Mordell-Weil rank.");
            }
            catch (DescentLimitException) { return Result("Saturation work limit reached; unlisted primes remain unresolved."); }
        }

        // A missing p-division modulo one good prime is an exact obstruction over Q.
        // Small fields only; the exact division equation is used when these filters do not decide.
        private static List<Func<EllipticCurvePoint, bool>> DivisionFilters(EllipticCurveQ e, int p, DescentBudget budget)
        {
            var result = new List<Func<EllipticCurvePoint, bool>>();
            foreach (int q in new[] { 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43 })
            {
                budget.Step();
                if (q == p || e.A4.Den % q == 0 || e.A6.Den % q == 0 || e.Discriminant.Num % q == 0 || e.Discriminant.Den % q == 0) continue;
                int ModQ(BigRational a) => (int)NativeNumberTheory.Mod(a.Num * BigInteger.ModPow(a.Den % q, q - 2, q), q);
                int a = ModQ(e.A4), b = ModQ(e.A6);
                var points = new List<(int x, int y)> { (-1, -1) };
                for (int x = 0; x < q; x++) for (int y = 0; y < q; y++) if ((y * y - ((x * x + a) * x + b)) % q == 0) points.Add((x, y));
                if (points.Count % p != 0) continue;
                int ModI(int n) => (n % q + q) % q;
                (int x, int y) AddMod((int x, int y) u, (int x, int y) v)
                {
                    if (u.x < 0) return v; if (v.x < 0) return u;
                    if (u.x == v.x && ModI(u.y + v.y) == 0) return (-1, -1);
                    int slope = ModI((u.x == v.x ? 3 * u.x * u.x + a : v.y - u.y) * (int)BigInteger.ModPow(ModI(u.x == v.x ? 2 * u.y : v.x - u.x), q - 2, q));
                    int x = ModI(slope * slope - u.x - v.x); return (x, ModI(slope * (u.x - x) - u.y));
                }
                var image = new HashSet<(int x, int y)>();
                foreach (var pt in points)
                {
                    budget.Step(); var v = pt; var sum = (-1, -1);
                    for (int k = p; k > 0; k >>= 1) { if ((k & 1) != 0) sum = AddMod(sum, v); v = AddMod(v, v); }
                    image.Add(sum);
                }
                result.Add(pt => image.Contains(pt.IsInfinity || pt.X.Den % q == 0 ? (-1, -1) : (ModQ(pt.X), ModQ(pt.Y))));
            }
            return result;
        }
    }
}
