namespace EllipticCurves
{
    /// <summary>Unconditional lower bound from supplied rational points. No upper bound or saturation is asserted.</summary>
    public sealed class PointRankCertificate
    {
        /// <summary>Proved lower bound for the rank of the subgroup generated by the supplied points.</summary>
        public int LowerBound { get; }
        /// <summary>Number of supplied points, including repetitions and infinity.</summary>
        public int PointCount { get; }
        /// <summary>Whether all supplied points are proved independent modulo torsion.</summary>
        public bool IndependenceCertified => LowerBound == PointCount;
        /// <summary>Rank of the combined binary character matrix.</summary>
        public int ImageDimension { get; }
        /// <summary>Upper bound for dim E(Q)[2], obtained from good reduction.</summary>
        public int TwoTorsionDimensionUpperBound { get; }
        /// <summary>Number of good odd primes used.</summary>
        public int GoodPrimeCount { get; }
        /// <summary>A good odd prime excluding rational 2-torsion, when one was found.</summary>
        public int? NoTwoTorsionPrime { get; }
        /// <summary>Meaning of the result, including the limitation of a finite set of characters.</summary>
        public string Reason => IndependenceCertified
            ? "All supplied points are independent modulo torsion. Only a rank lower bound is proved."
            : "Only a lower bound is proved. A smaller bound does not prove dependence; try more reduction primes.";
        internal PointRankCertificate(int pointCount, RationalPointRank certificate)
        {
            PointCount = pointCount; LowerBound = certificate.LowerBound; ImageDimension = certificate.ImageDimension;
            TwoTorsionDimensionUpperBound = certificate.TorsionDimensionUpperBound;
            GoodPrimeCount = certificate.GoodPrimeCount; NoTwoTorsionPrime = certificate.NoTwoTorsionPrime;
        }
    }
}
