<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>EllipticCurves.Explorer</AssemblyName>
    <RootNamespace>EllipticCurves.Explorer</RootNamespace>
    <StartupObject>EllipticCurves.Explorer.Program</StartupObject>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>../docs/ico/ec_logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="PresentationHost" />
    <Resource Include="../docs/png/ec_logo_v3a.png" Link="ec_logo.png" />
    <ProjectReference Include="../sources/EllipticCurves.csproj" />
  </ItemGroup>
</Project>
