<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <AssemblyName>EllipticCurves.Visualizer</AssemblyName>
    <RootNamespace>EllipticCurves.Visualizer</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>ec_logo.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="ec_logo.png" />
    <Resource Include="ec_logo.png" />
    <ProjectReference Include="../sources/EllipticCurves.csproj" />
  </ItemGroup>
</Project>
